dev-util/lief: add missing dep
* python3_11: running distutils-r1_run_phase distutils-r1_python_compile
 *   Building the wheel for LIEF-0.14.0/api/python via setup
python3.11 -m gpep517 build-wheel --prefix=/usr --backend setup --output-fd 3 --wheel-dir /var/tmp/portage/dev-util/lief-0.14.0/work/LIEF-0.14.0_build-python3_11/wheel
2024-02-09 05:54:01,076 gpep517 INFO Building wheel via backend setup
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 429, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 425, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 215, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 207, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/lief-0.14.0/work/LIEF-0.14.0/api/python/backend/setup.py", line 139, in build_wheel
    config_settings = _get_hooked_config(is_editable=False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/lief-0.14.0/work/LIEF-0.14.0/api/python/backend/setup.py", line 78, in _get_hooked_config
    from config import Config
  File "/var/tmp/portage/dev-util/lief-0.14.0/work/LIEF-0.14.0/api/python/backend/config.py", line 3, in <module>
    from pydantic import BaseModel, ValidationError, Field
ModuleNotFoundError: No module named 'pydantic'